export const FETCH_MULTI_SEARCH = 'FETCH_MULTI_SEARCH';  
export const FETCH_MULTI_SEARCH_SUCCESS = 'FETCH_MULTI_SEARCH_SUCCESS';  

export const FETCH_TRENDING = 'FETCH_TRENDING';  
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';  

export const IS_LOADED_HERO_IMAGE = 'IS_LOADED_HERO_IMAGE';  

export const SET_TRENDING_HERO_IMAGE = 'SET_TRENDING_HERO_IMAGE';  
export const SET_TRENDING_HERO_IMAGE_SUCCESS = 'SET_TRENDING_HERO_IMAGE_SUCCESS';  

export const FETCH_TRENDING_ALL_WEEK = 'FETCH_TRENDING_ALL_WEEK';  
export const FETCH_TRENDING_ALL_WEEK_SUCCESS = 'FETCH_TRENDING_ALL_WEEK_SUCCESS';  

export const FETCH_TRENDING_MOV_WEEK = 'FETCH_TRENDING_MOV_WEEK';  
export const FETCH_TRENDING_MOV_WEEK_SUCCESS = 'FETCH_TRENDING_MOV_WEEK_SUCCESS';  

export const FETCH_MOV_TOP_RATED = 'FETCH_MOV_TOP_RATED';  
export const FETCH_MOV_TOP_RATED_SUCCESS = 'FETCH_MOV_TOP_RATED_SUCCESS';

export const FETCH_MOV_POPULAR = 'FETCH_MOV_POPULAR';  
export const FETCH_MOV_POPULAR_SUCCESS = 'FETCH_MOV_POPULAR_SUCCESS';  

export const FETCH_TV_POPULAR = 'FETCH_TV_POPULAR';  
export const FETCH_TV_POPULAR_SUCCESS = 'FETCH_TV_POPULAR_SUCCESS';  

export const FETCH_MOV_UPCOMING = 'FETCH_MOV_UPCOMING';  
export const FETCH_MOV_UPCOMING_SUCCESS = 'FETCH_MOV_UPCOMING_SUCCESS';  

export const FETCH_GENRES_MOV_LABEL = 'FETCH_GENRES_MOV';  
export const FETCH_GENRES_MOV_LABEL_SUCCESS = 'FETCH_GENRES_MOV_SUCCESS';  
export const FETCH_GENRES_TV_LABEL = 'FETCH_GENRES_SUCCESS_TV';  
export const FETCH_GENRES_TV_LABEL_SUCCESS = 'FETCH_GENRES_TV_SUCCESS'; 

export const FETCH_SINGLE_GENRE = 'FETCH_SINGLE_GENRE';  
export const FETCH_SINGLE_GENRE_SUCCESS = 'FETCH_SINGLE_GENRE_SUCCESS';  

export const FETCH_DETAIL = 'FETCH_DETAIL';  
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';  

export const FETCH_CAST = 'FETCH_CAST';  
export const FETCH_CAST_SUCCESS = 'FETCH_CAST_SUCCESS';  

export const FETCH_LANGUAGE_CODE = 'FETCH_LANGUAGE_CODE';  
export const FETCH_LANGUAGE_CODE_SUCCESS = 'FETCH_LANGUAGE_CODE_SUCCESS';  

export const CAROUSEL_LOAD = 'CAROUSEL_LOAD';  
export const CAROUSEL_SCROLL_ON = 'CAROUSEL_SCROLL_ON';  
export const CAROUSEL_SCROLL_OFF = 'CAROUSEL_SCROLL_OFF';  